In [45]:
# Import necessary libraries
import pandas as pd
import math

### Exploratory Data Analysis (EDA)
### Melakukan analisis awal terhadap dataset untuk memahami struktur dan statistik descriptif

In [47]:
# Load dataset
dataset = pd.read_csv ('food_full.csv')

In [48]:
dataset

,Country,Real coffee,Instant coffee,Tea,Sweetener,Biscuits,Powder soup,Tin soup,Potatoes,Frozen fish,Apples,Oranges,Tinned fruit,Jam,Garlic,Butter
0,Germany,90,49,88,19.0,57.0,57,51,19,21,27,81,75,44.0,71,22
1,Italy,82,10,60,2.0,NaN,55,41,3,2,4,67,71,9.0,46,80
2,France,88,42,63,4.0,76.0,76,53,11,23,11,87,84,40.0,45,88
3,Holland,96,62,98,32.0,62.0,62,67,43,7,14,83,89,61.0,81,31
4,Belgium,94,38,48,11.0,74.0,74,37,23,9,13,76,76,42.0,57,29
5,Luxembourg,97,61,86,28.0,79.0,79,73,12,7,26,85,94,83.0,91,84
6,England,27,86,99,22.0,91.0,91,55,76,17,20,76,68,89.0,91,95
7,Portugal,72,26,77,NaN,22.0,22,34,1,5,20,22,51,NaN,16,65
8,Austria,55,31,61,15.0,29.0,29,33,1,5,15,49,42,14.0,51,51
9,Switzerland,73,72,85,25.0,31.0,31,69,10,17,19,79,70,46.0,64,82
10,Denmark,96,17,93,35.0,66.0,66,32,17,17,51,81,72,50.0,64,64
11,Norway,92,83,83,13.0,62.0,62,51,4,5,30,61,34,34.0,11,51
12,Ireland,30,52,99,11.0,80.0,80,75,18,18,5,57,52,46.0,89,97

### Checking for Missing Values
#### Using `isnull().sum()` to Find Missing Values

In [39]:
dataset.isnull().sum()

Country           0
Real coffee       0
Instant coffee    0
Tea               0
Sweetener         1
Biscuits          1
Powder soup       0
Tin soup          0
Potatoes          0
Frozen fish       0
Apples            0
Oranges           0
Tinned fruit      0
Jam               1
Garlic            0
Butter            0
dtype: int64

### Handling Missing Values
#### Using `fillna()` to Replace Missing Values

In [41]:
dataset['Sweetener'].fillna(math.floor(dataset['Sweetener'].mean()), inplace= True)
dataset['Biscuits'].fillna(math.floor(dataset['Biscuits'].mean()), inplace= True)
dataset['Jam'].fillna(math.floor(dataset['Jam'].mean()), inplace= True)

In [42]:
dataset

,Country,Real coffee,Instant coffee,Tea,Sweetener,Biscuits,Powder soup,Tin soup,Potatoes,Frozen fish,Apples,Oranges,Tinned fruit,Jam,Garlic,Butter
0,Germany,90,49,88,19.0,57.0,57,51,19,21,27,81,75,44.0,71,22
1,Italy,82,10,60,2.0,60.0,55,41,3,2,4,67,71,9.0,46,80
2,France,88,42,63,4.0,76.0,76,53,11,23,11,87,84,40.0,45,88
3,Holland,96,62,98,32.0,62.0,62,67,43,7,14,83,89,61.0,81,31
4,Belgium,94,38,48,11.0,74.0,74,37,23,9,13,76,76,42.0,57,29
5,Luxembourg,97,61,86,28.0,79.0,79,73,12,7,26,85,94,83.0,91,84
6,England,27,86,99,22.0,91.0,91,55,76,17,20,76,68,89.0,91,95
7,Portugal,72,26,77,18.0,22.0,22,34,1,5,20,22,51,46.0,16,65
8,Austria,55,31,61,15.0,29.0,29,33,1,5,15,49,42,14.0,51,51
9,Switzerland,73,72,85,25.0,31.0,31,69,10,17,19,79,70,46.0,64,82
10,Denmark,96,17,93,35.0,66.0,66,32,17,17,51,81,72,50.0,64,64
11,Norway,92,83,83,13.0,62.0,62,51,4,5,30,61,34,34.0,11,51
12,Ireland,30,52,99,11.0,80.0,80,75,18,18,5,57,52,46.0,89,97

In [44]:
dataset.isnull().sum()

Country           0
Real coffee       0
Instant coffee    0
Tea               0
Sweetener         0
Biscuits          0
Powder soup       0
Tin soup          0
Potatoes          0
Frozen fish       0
Apples            0
Oranges           0
Tinned fruit      0
Jam               0
Garlic            0
Butter            0
dtype: int64